import { jsPDF } from "jspdf";
import type { DocumentContent } from "@/types/documents";

// ── Color Helpers ────────────────────────────────────────────────────────────

function hexToRgb(hex: string): [number, number, number] {
  const h = hex.replace(/^#/, "");
  return [
    parseInt(h.substring(0, 2), 16),
    parseInt(h.substring(2, 4), 16),
    parseInt(h.substring(4, 6), 16),
  ];
}

function setFillColor(doc: jsPDF, color: string) {
  const [r, g, b] = hexToRgb(color);
  doc.setFillColor(r, g, b);
}

function setTextColor(doc: jsPDF, color: string) {
  const [r, g, b] = hexToRgb(color);
  doc.setTextColor(r, g, b);
}

function setDrawColor(doc: jsPDF, color: string) {
  const [r, g, b] = hexToRgb(color);
  doc.setDrawColor(r, g, b);
}

// ── Layout Constants ─────────────────────────────────────────────────────────

const PAGE_WIDTH = 210; // A4 mm
const PAGE_HEIGHT = 297;
const MARGIN_LEFT = 25;
const MARGIN_RIGHT = 25;
const MARGIN_TOP = 30;
const MARGIN_BOTTOM = 30;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN_LEFT - MARGIN_RIGHT;
const FOOTER_Y = PAGE_HEIGHT - 15;

// ── Theme ────────────────────────────────────────────────────────────────────

const COLORS = {
  primary: "#1a1a2e",
  secondary: "#16213e",
  accent: "#8b5cf6",
  accentLight: "#a78bfa",
  text: "#1f2937",
  textLight: "#6b7280",
  textWhite: "#ffffff",
  border: "#e5e7eb",
  bgLight: "#f9fafb",
};

// ── Shared Helpers ───────────────────────────────────────────────────────────

function addHeader(doc: jsPDF, companyName: string) {
  // Top accent bar
  setFillColor(doc, COLORS.accent);
  doc.rect(0, 0, PAGE_WIDTH, 4, "F");

  // Company name in header
  setTextColor(doc, COLORS.textLight);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text(companyName, MARGIN_LEFT, 12);

  // Thin separator line
  setDrawColor(doc, COLORS.border);
  doc.setLineWidth(0.3);
  doc.line(MARGIN_LEFT, 16, PAGE_WIDTH - MARGIN_RIGHT, 16);
}

function addFooter(doc: jsPDF, pageNum: number, totalPages: number, confidential: boolean) {
  // Separator line
  setDrawColor(doc, COLORS.border);
  doc.setLineWidth(0.3);
  doc.line(MARGIN_LEFT, FOOTER_Y - 5, PAGE_WIDTH - MARGIN_RIGHT, FOOTER_Y - 5);

  setTextColor(doc, COLORS.textLight);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);

  // Page number (right)
  doc.text(`Page ${pageNum} of ${totalPages}`, PAGE_WIDTH - MARGIN_RIGHT, FOOTER_Y, {
    align: "right",
  });

  // Confidential tag (left)
  if (confidential) {
    doc.text("CONFIDENTIAL", MARGIN_LEFT, FOOTER_Y);
  }

  // Generated by (center)
  doc.text("Generated by PitchDeck.biz", PAGE_WIDTH / 2, FOOTER_Y, {
    align: "center",
  });
}

function ensureSpace(doc: jsPDF, yPos: number, needed: number, companyName: string): number {
  if (yPos + needed > PAGE_HEIGHT - MARGIN_BOTTOM) {
    doc.addPage();
    addHeader(doc, companyName);
    return MARGIN_TOP;
  }
  return yPos;
}

// ── Main Export Function ─────────────────────────────────────────────────────

export async function generateDocumentPDF(
  content: DocumentContent,
): Promise<Buffer> {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const { companyName, date, confidential } = content.metadata;

  // ── Cover Page ────────────────────────────────────────────────────────────

  // Full-page dark background for cover
  setFillColor(doc, COLORS.primary);
  doc.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, "F");

  // Accent bar at top
  setFillColor(doc, COLORS.accent);
  doc.rect(0, 0, PAGE_WIDTH, 6, "F");

  // Company logo placeholder area
  setDrawColor(doc, COLORS.accentLight);
  doc.setLineWidth(0.5);
  doc.roundedRect(MARGIN_LEFT, 50, 40, 40, 3, 3, "S");
  setTextColor(doc, COLORS.accentLight);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text("LOGO", MARGIN_LEFT + 20, 73, { align: "center" });

  // Document title
  setTextColor(doc, COLORS.textWhite);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(32);

  // Derive title from first section or company name
  const docTitle =
    content.sections.length > 0
      ? content.sections[0].title
      : "Business Document";

  const titleLines = doc.splitTextToSize(docTitle, CONTENT_WIDTH);
  doc.text(titleLines, MARGIN_LEFT, 120);

  // Company name under title
  let coverY = 120 + titleLines.length * 14 + 10;
  setTextColor(doc, COLORS.accentLight);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(16);
  doc.text(companyName, MARGIN_LEFT, coverY);
  coverY += 12;

  // Date
  setTextColor(doc, COLORS.textLight);
  doc.setFontSize(11);
  const formattedDate = new Date(date).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  doc.text(formattedDate, MARGIN_LEFT, coverY);
  coverY += 8;

  // Confidential marker
  if (confidential) {
    coverY += 5;
    setTextColor(doc, COLORS.accent);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text("CONFIDENTIAL", MARGIN_LEFT, coverY);
  }

  // Bottom accent bar on cover
  setFillColor(doc, COLORS.accent);
  doc.rect(0, PAGE_HEIGHT - 6, PAGE_WIDTH, 6, "F");

  // ── Content Pages ─────────────────────────────────────────────────────────

  doc.addPage();
  addHeader(doc, companyName);
  let yPos = MARGIN_TOP;

  for (let i = 0; i < content.sections.length; i++) {
    const section = content.sections[i];

    // Section title
    yPos = ensureSpace(doc, yPos, 20, companyName);

    // Accent line before section title
    setFillColor(doc, COLORS.accent);
    doc.rect(MARGIN_LEFT, yPos - 2, 3, 10, "F");

    setTextColor(doc, COLORS.primary);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    const sectionTitleLines = doc.splitTextToSize(
      section.title.toUpperCase(),
      CONTENT_WIDTH - 8,
    );
    doc.text(sectionTitleLines, MARGIN_LEFT + 8, yPos + 6);
    yPos += sectionTitleLines.length * 7 + 12;

    // Section body
    yPos = ensureSpace(doc, yPos, 15, companyName);
    setTextColor(doc, COLORS.text);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);

    const bodyLines = doc.splitTextToSize(section.body, CONTENT_WIDTH);
    // Render body line-by-line to handle page breaks
    for (const line of bodyLines) {
      yPos = ensureSpace(doc, yPos, 6, companyName);
      doc.text(line, MARGIN_LEFT, yPos);
      yPos += 4.5;
    }
    yPos += 6;

    // Subsections
    if (section.subsections && section.subsections.length > 0) {
      for (const sub of section.subsections) {
        yPos = ensureSpace(doc, yPos, 15, companyName);

        // Subsection title
        setTextColor(doc, COLORS.accent);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(11);
        doc.text(sub.title, MARGIN_LEFT + 5, yPos);
        yPos += 7;

        // Subsection body
        setTextColor(doc, COLORS.text);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        const subLines = doc.splitTextToSize(sub.body, CONTENT_WIDTH - 5);
        for (const line of subLines) {
          yPos = ensureSpace(doc, yPos, 6, companyName);
          doc.text(line, MARGIN_LEFT + 5, yPos);
          yPos += 4.5;
        }
        yPos += 5;
      }
    }

    // Section divider (except last section)
    if (i < content.sections.length - 1) {
      yPos = ensureSpace(doc, yPos, 10, companyName);
      setDrawColor(doc, COLORS.border);
      doc.setLineWidth(0.3);
      doc.line(MARGIN_LEFT, yPos, PAGE_WIDTH - MARGIN_RIGHT, yPos);
      yPos += 10;
    }
  }

  // ── Add footers to all content pages ───────────────────────────────────────

  const totalPages = doc.getNumberOfPages();
  // Skip cover page (page 1), add footers to pages 2+
  for (let p = 2; p <= totalPages; p++) {
    doc.setPage(p);
    addFooter(doc, p - 1, totalPages - 1, confidential);
  }

  return Buffer.from(doc.output("arraybuffer"));
}
