import JSZip from "jszip";
import type { DeckContent } from "@/lib/types";
import type { BrandColors } from "./pptx-generator";
import { generatePptx } from "./pptx-generator";
import {
  generateSellSheetPDF,
  generateOnePagerPDF,
  generateBrandKitPDF,
} from "./pdf-generator";

const DEFAULT_BRAND_COLORS: BrandColors = {
  primary: "#1a1a2e",
  secondary: "#16213e",
  accent: "#e94560",
  text: "#ffffff",
  background: "#0f0f23",
};

// ── ZIP Bundle Generator ─────────────────────────────────────────────────────

export async function generateBundle(
  deck: DeckContent,
  brandColors: BrandColors = DEFAULT_BRAND_COLORS
): Promise<Buffer> {
  const zip = new JSZip();

  // Generate all files in parallel
  const [pptxBuffer, sellSheetBuffer, onePagerBuffer, brandKitBuffer] =
    await Promise.all([
      generatePptx(deck, brandColors),
      generateSellSheetPDF(deck, brandColors),
      generateOnePagerPDF(deck, brandColors),
      generateBrandKitPDF(deck, brandColors),
    ]);

  // Add files to ZIP
  zip.file("pitch-deck.pptx", pptxBuffer);
  zip.file("sell-sheet.pdf", sellSheetBuffer);
  zip.file("one-pager.pdf", onePagerBuffer);
  zip.file("brand-kit.pdf", brandKitBuffer);

  // Add README
  const readme = buildReadme(deck);
  zip.file("README.txt", readme);

  // Generate ZIP buffer
  const zipBuffer = await zip.generateAsync({
    type: "nodebuffer",
    compression: "DEFLATE",
    compressionOptions: { level: 6 },
  });

  return Buffer.from(zipBuffer);
}

// ── README Builder ───────────────────────────────────────────────────────────

function buildReadme(deck: DeckContent): string {
  const title = deck.slides[0]?.title ?? "Pitch Deck";
  const slideCount = deck.slides.length;

  return `${title}
${"=".repeat(title.length)}

Generated by PitchDeck.biz

Contents:
---------
1. pitch-deck.pptx    - ${slideCount}-slide pitch deck presentation
2. sell-sheet.pdf      - 1-2 page sell sheet for investors/partners
3. one-pager.pdf       - Single-page executive summary
4. brand-kit.pdf       - Brand guidelines (colors, typography, voice)

Slide Overview:
---------
${deck.slides.map((s) => `  ${s.slideNumber}. [${s.type}] ${s.title}`).join("\n")}

---
Questions? Visit https://pitchdeck.biz
`;
}
