import type { Metadata } from "next"
import Link from "next/link"
import { Header } from "@/components/layout/header"
import { Footer } from "@/components/layout/footer"
import { GradientBar } from "@/components/ui/gradient-bar"
import { createPageMetadata } from "@/lib/metadata"
import { ArrowUpRight } from "lucide-react"

export const metadata: Metadata = createPageMetadata({
  title: "Our Work — AI-Generated Pitch Decks",
  description:
    "See examples of investor-ready pitch decks, sell sheets, and branding kits generated by pitchdeck.biz AI.",
  path: "/work",
})

const PORTFOLIO_ITEMS = [
  {
    title: "SaaS Analytics Platform",
    industry: "Enterprise Software",
    investorType: "Venture Capital",
    round: "Series A",
    slides: 12,
    gradient: "from-[#7c3aed] to-[#3b82f6]",
    description:
      "A data-driven pitch deck for a B2B analytics platform targeting Series A VCs. Emphasized market size ($50B TAM), growth metrics, and competitive moat.",
  },
  {
    title: "Sustainable Fashion Brand",
    industry: "Consumer / DTC",
    investorType: "Angel Investor",
    round: "Pre-Seed",
    slides: 12,
    gradient: "from-[#ec4899] to-[#f97316]",
    description:
      "A founder-story-driven deck for an eco-conscious clothing brand. Highlighted early traction, community building, and sustainability impact metrics.",
  },
  {
    title: "HealthTech Diagnostics",
    industry: "Healthcare",
    investorType: "Venture Capital",
    round: "Seed",
    slides: 14,
    gradient: "from-[#06b6d4] to-[#10b981]",
    description:
      "An investor-tailored deck for an AI diagnostics startup. Focused on FDA pathway, clinical validation data, and addressable market in remote diagnostics.",
  },
  {
    title: "Local Restaurant Chain",
    industry: "Food & Beverage",
    investorType: "Bank / SBA",
    round: "SBA Loan",
    slides: 10,
    gradient: "from-[#f97316] to-[#7c3aed]",
    description:
      "A bank-ready business deck emphasizing cash flow projections, collateral, repayment ability, and 3-year financial stability for expansion financing.",
  },
  {
    title: "EdTech Learning Platform",
    industry: "Education",
    investorType: "Crowdfunding",
    round: "Kickstarter",
    slides: 12,
    gradient: "from-[#3b82f6] to-[#06b6d4]",
    description:
      "A community-focused campaign deck with emotional storytelling, social proof from beta users, reward tier breakdown, and viral sharing strategy.",
  },
  {
    title: "CleanTech Energy Storage",
    industry: "Energy / Climate",
    investorType: "Family Office",
    round: "Series B",
    slides: 12,
    gradient: "from-[#10b981] to-[#3b82f6]",
    description:
      "A long-term value proposition deck for family office investors. Emphasized ESG impact alignment, sustainable returns, and 10-year market trajectory.",
  },
]

const STATS = [
  { value: "500+", label: "Pitch Decks Generated" },
  { value: "6", label: "Investor Type Profiles" },
  { value: "< 5 min", label: "Average Generation Time" },
  { value: "4", label: "Deliverables Per Deck" },
]

export default function WorkPage() {
  return (
    <>
      <Header />
      <main className="pt-24 pb-20">
        {/* Hero */}
        <section className="max-w-[1280px] mx-auto px-6 md:px-12 mb-20">
          <div className="max-w-3xl">
            <p className="text-sm text-muted-foreground uppercase tracking-wider mb-4">
              Our Work
            </p>
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-semibold tracking-tight text-balance">
              Pitch Decks That Win Funding
            </h1>
            <p className="mt-6 text-lg text-muted-foreground leading-relaxed max-w-2xl">
              Every deck is custom-built from your business data and tailored to
              your target investor type. Here are examples of what our AI
              creates.
            </p>
          </div>

          {/* Stats */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mt-12">
            {STATS.map((stat) => (
              <div
                key={stat.label}
                className="rounded-xl border border-border bg-card p-5 text-center"
              >
                <p
                  className="text-2xl md:text-3xl font-bold"
                  style={{ color: "var(--brand-primary)" }}
                >
                  {stat.value}
                </p>
                <p className="text-sm text-muted-foreground mt-1">
                  {stat.label}
                </p>
              </div>
            ))}
          </div>
        </section>

        {/* Portfolio Grid */}
        <section className="max-w-[1280px] mx-auto px-6 md:px-12 mb-20">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {PORTFOLIO_ITEMS.map((item) => (
              <div
                key={item.title}
                className="group rounded-xl border border-border bg-card overflow-hidden transition-all duration-300 hover:border-primary/30 hover:shadow-lg hover:-translate-y-1"
              >
                {/* Gradient header */}
                <div
                  className={`h-40 bg-gradient-to-br ${item.gradient} relative overflow-hidden`}
                >
                  {/* Grid pattern */}
                  <div
                    className="absolute inset-0 opacity-[0.07]"
                    style={{
                      backgroundImage:
                        "linear-gradient(rgba(255,255,255,0.3) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.3) 1px, transparent 1px)",
                      backgroundSize: "24px 24px",
                    }}
                  />
                  {/* Slide count badge */}
                  <div className="absolute top-3 right-3 px-2.5 py-1 rounded-full bg-black/30 backdrop-blur-sm text-xs font-medium text-white">
                    {item.slides} slides
                  </div>
                  {/* Mockup placeholder */}
                  <div className="absolute bottom-4 left-4 right-4">
                    <div className="bg-white/10 backdrop-blur-sm rounded-lg p-3">
                      <div className="h-2 w-3/4 rounded-full bg-white/30 mb-2" />
                      <div className="h-1.5 w-full rounded-full bg-white/15 mb-1.5" />
                      <div className="h-1.5 w-5/6 rounded-full bg-white/15" />
                    </div>
                  </div>
                </div>

                {/* Content */}
                <div className="p-5">
                  <div className="flex items-center gap-2 mb-2">
                    <span className="text-xs font-medium px-2 py-0.5 rounded-full bg-primary/10 text-primary">
                      {item.investorType}
                    </span>
                    <span className="text-xs text-muted-foreground">
                      {item.round}
                    </span>
                  </div>
                  <h3 className="text-lg font-semibold mb-1">{item.title}</h3>
                  <p className="text-xs text-muted-foreground mb-3">
                    {item.industry}
                  </p>
                  <p className="text-sm text-muted-foreground leading-relaxed">
                    {item.description}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* CTA */}
        <section className="max-w-[1280px] mx-auto px-6 md:px-12">
          <div
            className="rounded-2xl p-10 md:p-14 text-center"
            style={{
              background:
                "linear-gradient(135deg, rgba(124, 58, 237, 0.08), rgba(236, 72, 153, 0.06))",
              border: "1px solid rgba(124, 58, 237, 0.2)",
            }}
          >
            <h2 className="text-2xl md:text-3xl font-semibold tracking-tight mb-4">
              Ready to Create Your Own?
            </h2>
            <p className="text-muted-foreground mb-8 max-w-lg mx-auto">
              Tell us about your business and our AI will generate an
              investor-ready pitch deck tailored to your target investors.
            </p>
            <Link
              href="/create"
              className="inline-flex items-center gap-2 px-8 py-4 text-base font-semibold text-white rounded-full transition-all hover:scale-105 brand-gradient-glow"
              style={{
                background: "var(--brand-gradient-cta)",
                boxShadow: "0 8px 32px rgba(124, 58, 237, 0.4)",
              }}
            >
              Create Your Pitch Deck
              <ArrowUpRight className="w-4 h-4" />
            </Link>
          </div>
        </section>
      </main>
      <Footer />
      <GradientBar />
    </>
  )
}
