"use client"

import Image from "next/image"
import { SectionTitle } from "@/components/ui/section-title"

const examples = [
  {
    id: 1,
    title: "Investor Pitch Deck",
    category: "Fundraising",
    description: "AI-generated 15-slide pitch deck covering problem, solution, market, team, and financials",
    image: "/images/deliverable-pitch-deck.png",
    tags: ["Pitch Deck", "PPTX", "PDF"],
  },
  {
    id: 2,
    title: "Business Sell Sheet",
    category: "Sales Collateral",
    description: "Professional one-page sell sheet designed for partner meetings and trade shows",
    image: "/images/deliverable-sell-sheet.png",
    tags: ["Sell Sheet", "PDF", "Print-Ready"],
  },
  {
    id: 3,
    title: "Executive One-Pager",
    category: "Executive Summary",
    description: "Concise single-page summary capturing everything investors need to know",
    image: "/images/deliverable-one-pager.png",
    tags: ["One-Pager", "PDF", "Summary"],
  },
  {
    id: 4,
    title: "Complete Branding Kit",
    category: "Brand Identity",
    description: "Logo concepts, color palette, typography, and brand guidelines generated by AI",
    image: "/images/deliverable-branding-kit.png",
    tags: ["Branding", "Logo", "Style Guide"],
  },
]

export function SelectedWorks() {
  return (
    <section id="works" className="py-20 md:py-10 md:pt-32 pb-4">
      <div className="max-w-[1280px] mx-auto px-6 md:px-12">
        {/* Section Header */}
        <div className="flex items-center justify-between mb-12 md:mb-16">
          <SectionTitle className="text-3xl md:text-4xl lg:text-5xl font-semibold tracking-tight">
            What We Deliver
          </SectionTitle>
        </div>

        <div className="relative">
          {examples.map((work, index) => (
            <div
              key={work.id}
              className="sticky"
              style={{
                top: `${70 + index * 0}px`,
                zIndex: index + 1,
              }}
            >
              <div className="group block pt-10">
                <article className="overflow-hidden rounded-2xl md:rounded-3xl border border-border bg-card transition-all duration-300 hover:shadow-lg hover:-translate-y-1">
                  {/* Image */}
                  <div className="relative aspect-[2/1] overflow-hidden bg-secondary">
                    <Image
                      src={work.image}
                      alt={work.title}
                      fill
                      className="object-cover transition-transform duration-500 group-hover:scale-105"
                    />
                  </div>

                  {/* Content */}
                  <div className="p-3 md:p-3">
                    <div className="flex items-start justify-between gap-4">
                      <div>
                        <h3 className="text-lg md:text-xl font-semibold">{work.title}</h3>
                        <p className="text-sm text-muted-foreground mt-1">{work.description}</p>
                      </div>
                    </div>

                    {/* Tags */}
                    <div className="flex flex-wrap gap-2 mt-4">
                      {work.tags.map((tag) => (
                        <span
                          key={tag}
                          className="px-3 py-1 text-xs font-medium bg-secondary text-secondary-foreground rounded-full"
                        >
                          {tag}
                        </span>
                      ))}
                    </div>
                  </div>
                </article>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}
